server:
  port: 8081

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
    url: jdbc:h2:mem:skylab
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: true
    sql:
      init.mode: always
